#!/bin/bash
set -e

BUILD_DEBUG="${BUILD_DEBUG:-}"
if [[ -n "${BUILD_DEBUG}" ]]; then
    set -x
    env
fi

cd $(dirname $0)/..

echo "Bootstrapping..."
yarn --pure-lockfile install

source scripts/version
echo "BRANCH: ${COMMIT_BRANCH:-<none>}"
echo "TAG: ${GIT_TAG:-<none>}"
DIR=${GIT_TAG:-$COMMIT_BRANCH}

PROJECT=$(basename $(pwd))

BASE="${BASE:-https://releases.rancher.com/${PROJECT}}"
RESOURCE_BASE="${BASE}/${DIR}"

echo "Building for ${RESOURCE_BASE}..."

OUTPUT_DIR=dist/${DIR} ROUTER_BASE="/dashboard" RESOURCE_BASE="${RESOURCE_BASE}" yarn run build --spa
